# Generated by Django 3.1.5 on 2021-01-30 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210130_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='\\+1\\d{9,10}$')]),
        ),
    ]
